// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetTodoList() {
  return window['go']['main']['App']['GetTodoList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MarkAsComplete(arg1) {
  return window['go']['main']['App']['MarkAsComplete'](arg1);
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}
