// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string):Promise<Array<main.Todo>>;

export function CloseApp():Promise<void>;

export function DeleteTask(arg1:number):Promise<Array<main.Todo>>;

export function GetTodoList():Promise<Array<main.Todo>>;

export function Greet(arg1:string):Promise<string>;

export function MarkAsComplete(arg1:number):Promise<Array<main.Todo>>;

export function Minimize():Promise<void>;
